### ISSUE TITLE
Not working with Shaarli v0.10.2

### ISSUE THREAD

**Issue by haysebeyse** [ManufacturaInd/shaarli-2004licious-theme#8]
Home page is not showing any links. Swithing back to default theme fixes the problem. Apache log with this theme enabled:

`
[Tue Oct 02 22:32:37.455129 2018] [php7:error] [pid 29136] [client 65.31.67.170:60617] PHP Fatal error:  Uncaught Error: Call to undefined function thumbnail() in /var/www/xxxxx.com/html/links/tmp/linklist.5a015af2c145452a88719e7f7f99643b.rtpl.php:63\nStack trace:\n#0 /var/www/xxxxx.com/html/links/inc/rain.tpl.class.php(175): include()\n#1 /var/www/xxxxx.com/html/links/application/PageBuilder.php(188): RainTPL->draw('linklist')\n#2 /var/www/xxxxx.com/html/links/index.php(497): PageBuilder->renderPage('linklist')\n#3 /var/www/xxxxx.com/html/links/index.php(1549): showLinkList(Object(PageBuilder), Object(LinkDB), Object(Shaarli\\Config\\ConfigManager), Object(PluginManager), Object(Shaarli\\Security\\LoginManager))\n#4 /var/www/xxxxx.com/html/links/index.php(1866): renderPage(Object(Shaarli\\Config\\ConfigManager), Object(PluginManager), Object(LinkDB), Object(History), Object(Shaarli\\Security\\SessionManager), Object(Shaarli\\Security\\LoginManager))\n#5 {main}\n  thrown in /var/www/xxxxx.com/html/links/tmp/linklist.5a015af2c145452a88719e7f7f99643b.rtpl.php on line 63, referer: https://xxxxx.com/links/tpl/shaarli-2004licious-theme/css/shaarli.css`

**Comment by xuv** [comment]
@bisherbas Thanks for the report. I've just checked and it's actually more than the homepage that is broken. Also the login and Picwall and probably others. Will need to spend some time fixing this.

If you really want to use this theme, it works with Shaarli 0.9 for now without trouble.

**Comment by bisherbas** [comment]
@xuv Thank you for the response. I guess I can wait until you release a working version. I'm not in a hurry. Good luck!

**Comment by dajare** [comment]
Just to say: I came looking for a "compact" theme for Shaarli, and this "2004licious" is just about the only option! I sincerely hope it can be maintained for the latest releases. Thanks for your work on this, @xuv !

**Comment by dajare** [comment]
See also this issue on the Shaarli repo: "[‘Compact’ link list view #1328][1]"

[1]: https://github.com/shaarli/Shaarli/issues/1328

**Comment by haysebeyse** [comment]
Duplicate.

**Comment by xuv** [comment]
@meminens FYI, current version of the them works with 0.14

**Comment by dajare** [comment]
@xuv Fantastic! I just tried it with a test install of Shaarli v. 13.0 that I have, and it worked great with that, too. This is the first time I've been able to use 2004licious theme with Shaarli since I started using it ... quite a few years ago now! Thanks for your work on it.
